<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Stefan Dollinger">
<meta name="author" content="Lars Hinrichs">

<title>Canadian language attitudes from ‘coast to coast to coast’: On the pluricentricity of English</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Canadian language attitudes from ‘coast to coast to coast’: On the pluricentricity of English</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Stefan Dollinger </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of British Columbia
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Lars Hinrichs </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            The University of Texas at Austin
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>1 Introduction</h1>
<p>The present paper explores key aspects of the linguistic autonomy and the character, recognition and social embedding of “Standard Canadian English”. A focus on the standard of a given context, its conceptualization, perception and discursive construction is sociolinguistically relevant for several reasons. One can argue that attitudes towards a standard variety shape other aspects of linguistic practice. As sociolinguists are not immune to wider social developments we may expect shifting interpretations over time. For instance, while the first generation of Canadian linguists tended to emphasize differences &nbsp;between Canadian English and other varieties, above all American English (e.g.&nbsp;Avis et al.&nbsp;1967, Scargill 1974), the linguistics of Canadian English has seen a different effect in the era of the free trade negotiations of the 1980s and early 1990s<a href="#_ftn1">[1]</a>. This period was marked by statements as to the weakness of Canada-US border as a linguistic divide (e.g.&nbsp;Chambers 1980, Warkentyne &amp; Brett 1981: 307, Warkentyne 1983: 73), or even to its irrelevance (e.g.&nbsp;Woods 1993: 174). The latter point is only occasionally echoed in more recent writings (e.g.&nbsp;Sadlier-Brown 2012: 547).</p>
<p>What generally unites these claims, however, is the lack of a comparative US sample in addition to Canadian samples, which means that US usage is inferred from circumstantial evidence (e.g.&nbsp;dictionary and usage guides, or general impressions) but not based on data collected in the same way as on the Canadian side. Whenever a more rigorous design is brought to study cross-border linguistic influences, however, the relevance&nbsp; of the Canada-US border is shown and its linguistic effects – subtle yet consistent – become evident (e.g.&nbsp;Chambers 1994, 2000; Boberg 2000, Boberg 2005, Boberg 2008; Dollinger 2012) and the pluricentric character of North American English – with a dominant US Standard and a non-dominant Canadian Standard – is accepted.</p>
<p>By “pluricentric” we refer to pluricentric theory as applied by Clyne (1995) and Muhr (2025). A pluricentric language is defined as “a language with several interacting centres, each providing a national variety with at least some of its own (codified) norms” (Clyne 1995: 20). The notion of centre is to be taken in an abstract manner, there is not need for a physical centre (as in Canada), though there often is.&nbsp; In the context of pluricentric languages, it is noteworthy that “contiguous varieties” of the same language, such as Canadian and American English, or, in the European context, Austrian German and German German or Netherlandic and Belgian Dutch, have traditionally been faced with disciplinary scepticism that questions the reality of younger linguistic varieties varieties &nbsp;(e.g.&nbsp;Scherr &amp; Ziegler 2023).</p>
<p>By contrast, “non-contiguous varieties”, i.e.&nbsp;those separated by a sea border such as Australian and New Zealand English, or Irish English and English English, have been recognized as autonomous more easily. Such questions of dominance (heteronomy) or non-dominance (autonomy) are part and parcel of the sociolinguistic theory of linguistic pluricentricity (e.g.&nbsp;Clyne 1984, 1995, Muhr 2012, Dollinger 2019b). The terms “dominant” and “non-dominant” derive from Clyne (1995) to express that the social fact that the “relation [between pluricentric varieties] is usually asymmetric and the norms of the dominant variety are preferred” in some contexts (Muhr 2025: 17-18).</p>
<p>Based on a language attitudinal questionnaire, the present paper explores notions of the “standard” for Canadian English and notions of linguistic autonomy as central tenets of pluricentric theory. It is structured in the following way: after a brief overview of existing attitudinal work on Canadian English, we will first introduce the present data set, collected in late 2023. We will then discuss the main results, correlations and modelling effects for the 3000-respondent-survey. In a next step, the findings will be placed into the context of existing literature on language attitudes and perceptions and Canadian English, before they are interpreted in the larger framework of the sociolinguistic theory of pluricentricity. It will be highlighted that pluricentricity has been the dominant approach in the sociolinguistics of World Englishes and that other concepts, purported to stand in competition or to “complement” pluricentricity, appear in philological frames that not only face decolonial or dehegemonic challenges (e.g.&nbsp;Oakes 2021, Dollinger 2025a, 2025b) but that appear to be epistemologically fraught (Dollinger 2019b).</p>
<p>As pluricentric modelling does not lend itself well to data-driven perspectives that disregard the social salience of variables and speaker attitudes (e.g.&nbsp;Elspaß et al.&nbsp;2025, Scherr &amp; Ziegler 2023), we recognize the central role of speakers’ emic perspectives, i.e.&nbsp;the cognitive representation of multiple standard varieties in North America, in addition to etic dimension, i.e.&nbsp;linguistic production. Following de Cillia &amp; Ransmayr (2019), we employ non-linguistic terminology in our questions to probe the identification, conceptualization, and acceptance of a non-dominant standard variety, in our case Standard Canadian English (StCanE) in opposition to Standard American English, as indicative of multiple standards and thus linguistic pluricentricity in North America.</p>
</section>
<section id="literature" class="level1">
<h1>2 Literature</h1>
<p>Following Leitner (1992), two English varieties can be considered dominant today: Standard English English and Standard American English. All other varieties, including Standard Canadian English, are non-dominant varieties (e.g.&nbsp;Clyne 1992, originally called “non-dominant” “other” varieties) and are particularly prone to the effects of linguistic insecurity (Preston 2013). It is one purpose of this study to assess the belief of Canadians in the linguistic autonomy of their own standard, Standard Canadian English.</p>
<p>A few studies have hitherto investigated the phenomenon of linguistic attitudes and have either focussed on impressionistic assessment or on the linguistic insecurity among Canadian English speakers. Chambers (1986) surmises that Canadians, because of a higher degree of variation in spelling across provinces, are generally not favourable towards linguistic standards. Attitudinal data at the time suggested that Canadian English was orienting towards an American Standard in the early 1980s, although 1 in 4 Winnipeggers still considered the British form as “correct” (Owens and Baker 1984: 349).</p>
<p>Earlier attitudinal work sought to correlate measurements of attitudes towards country and statehood with linguistic features. Warkentyne (1983) and Gulden (1979) report on the same study, conducted in 1977 at the University of Victoria undergraduate in linguistics cohort. Gulden (1979: 45) reports on 64 students, while Warkentyne (1983: 72) speaks of “68 Canadian-born in two introductory English linguistics courses”, and “most of them indicated” to be “preparing for a career as teachers of English” (Gulden 1979: 45). Their results, however, are completely identical.</p>
<p><strong>The 1977 UVic student study</strong></p>
<p>The UVic study assessed on the one hand respondents’ general attitudes towards Canada, the US and the UK and on the other measured more specifically Canadian national identity with three questions:</p>
<p>a. questions about an obligation to buy Canadian products,</p>
<p>b. an evaluation of Canadian-produced TV programmes,</p>
<p>c. and a direct question about the existence of a Canadian national identity</p>
<p>(Gulden 1979: 57)</p>
<p>The study assessed attitudes on a scale from -1 (negative) to +1 (positive). General national identity was assessed at +0.292, so slightly positive in this student cohort of a median age of 23, while for the linguistic items the score was lower with +0.193, leading the researchers to conclude that “This group of Canadians does not feel very strongly about speaking a distinctive variety of English called Canadian English” (Gulden 1979: 58, Warkentyne 1983: 73, Table 1). The linguistic assessment was based on the following questions:</p>
<p>d.&nbsp;&nbsp;&nbsp;&nbsp; Is the language of CBC announcers the standard for spoken Canadian English?</p>
<p>e.&nbsp;&nbsp;&nbsp;&nbsp; Should a Canadian be offended if people from other countries consider him to be an American?</p>
<p>f.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; How should he feel if taken for British?</p>
<p>g.&nbsp;&nbsp;&nbsp;&nbsp; Does it make sense at all to speak of Canadian English as different from American and British English?</p>
<p>Answer options appeared in six intervals from -1 (negative) to +1 (positive). Some of these questions appear somewhat loaded (“does it make sense at all”; would a classification of Canadians as Americans “offend” a Canadian). In our questionnaire, similar questions were &nbsp;used in the present study with there-extrapositions or Yes/No questions on Likert scales.</p>
<p>Interesting in this context is the finding that questions “asking about Canadian identity directly show the most positive answers” (ibid: 58), which would relate to questions [c] and [g] above. For question [c] the value is +0.563, for the linguistic identity, [g], it is +0.344. It is possible that the rather negative framing of [g] underreported linguistic identity assessments, leading Gulden to summarize that “Canadians, or at least the present group, seem to believe in their national and linguistic identity, possibly more so than the low value of the entire [compound] variable would suggest” (ibid: 58) and lists as possible causes “an unfortunate choice of questions and/or by intervening factors such as modesty or insecurity” (ibid: 109). We have reason to assume that linguistic insecurity needs to be mitigated against, especially in non-dominant standard variety settings, such as Canadian English.</p>
<p>The study’s general national identity results, however, do not always fare positively for Canadian-ness. As Table 1 shows, the teacher’s degree students rated the U.S. “higher as a country in general” over Canada (ibid: 115), and, more strongly so, the U.K. over Canada and the U.K over the US:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(1)&nbsp;&nbsp; Preference ratings</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>US (-1) vs.&nbsp;Canada (+1)</td>
<td></td>
<td>-0.219</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>UK (-1) vs.&nbsp;Canada (+1)</td>
<td></td>
<td>-0.382</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>UK (-1) vs.&nbsp;US (+1)</td>
<td></td>
<td>-0.395</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>UK (-1) vs.&nbsp;US (+1) benefits</td>
<td></td>
<td>-0.307</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(2)&nbsp;&nbsp; Canadian national identity</td>
<td></td>
<td>+0.292</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Canadian linguistic identity</td>
<td></td>
<td>+0.193</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(3)&nbsp;&nbsp; Personality ratings</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Americans</td>
<td></td>
<td>+0.129</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>British</td>
<td></td>
<td>+0.222</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Canadians</td>
<td></td>
<td>+0.205</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Table 1: Attitudinal ratings in 1977, UVic students (Warkentyne 1983: Table 1)</p>
<p>The fourth line in the preference ratings refers to impressions of the perceived benefits that an association with the UK or the US offers to Canada. In 1977, this sample was clearly on the UK side. More generally, British people were rated more positively than Canadian people, but the Americans the lowest. Warkentyne comments that the “low scores on the items concerning Canadian identity should allay any fears that nationalism may be carried to the extreme” (1983: 73). Discussing correlations, including those about self-ratings and satisfaction in general, Gulden concludes “a striking combination”: “those who do not have a very high opinion of themselves or any other people (except Americans) are more likely to favour the U.S. over the U.K.” and those who show a high self-evaluation “are correlated with a preference for the U.K. over the U.S.” (ibid: 123-4).</p>
<p><strong>The 2000s: an increase of Canadian linguistic awareness</strong></p>
<p>A generation later, studies that use direct questions to assess respondents’ attitudes towards linguistic autonomy found that scores had markedly improved, with considerable majorities offering affirmative responses. A 2009 Vancouver study found that:</p>
<ul>
<li><p>81% believed that “there is a Canadian way of speaking English”</p></li>
<li><p>73% claimed to be able to “tell Canadian English speakers from American English speakers”</p></li>
<li><p>69% considered “Canadian English are part of [their] Canadian identity”</p></li>
<li><p>74% wanted Canadian English “taught in schools, using Canadian dictionaries, grammars etc.” (2009 data, Dollinger 2020: Table 4.5)</p></li>
</ul>
<p>Positive assessment can also be seen in terms of domestic linguistic attitudes. McKinnie &amp; Dailey-O’Cain (2002) polled Ontarians’ and Albertans’ assessments of “pleasantness” and “correctness” of varieties of Canadian English. In terms of “correctness”, both Albertans and Ontarians consider BC English as most correct (ibid: 283). A paper on 6–12-year-old elementary students and their parents in BC and Alberta found that 69% considered the Standard Canadian English speaker as “sounding Canadian”, while the Mandarin and Cantonese-accented speaker scored 26 and 23% respectively (Dollinger, Chan, Pasula &amp; Maag 2024: 326). This difference shows “a bias towards a StCanE accent which we attribute to the forcefulness of standard language ideology in Canada” (ibid). It was also shown that “the multilingual speaker is less tolerant towards L2-accented English than monolingual speakers” (ibid: 329).</p>
<p>What is available to date for assessments of Standard Canadian English are province-related findings from Manitoba, Alberta, Ontario and BC, but no study of national scope. One recent exception is Freake (2023: 196-7), a perceptual dialectology and language regard study on Canadian English with a national sample, confirming perceived dialect regions within the country. The present study hits in the same curb by offering solid data from all provinces and territories. It intends to gauge to what degree “Canadian English has become a reality for many of its speakers” (Dollinger 2019a: 224).</p>
</section>
<section id="the-data" class="level1">
<h1>3 The data</h1>
<p>The data was collected with a questionnaire of 25 language attitude and usage questions, which was complemented by 14 social background question. Data was collected with 18 students in an upper level English linguistics seminar at UBC (ENGL 489, Language Majors Seminar) in November and December 2023. The questionnaire can be accessed online. Over 3000 responses were collected, from all ten provinces and three territories, of which up to 3001 were used in the analysis. Table 1 shows the absolute &nbsp;numbers of responses by place of residence (Live now) and formative region, that is the region in which at least 9 years during the formative years 0-18 were spent. Because of low returns from residents of the territories (one from Nunavut (1) and case numbers in the mid-teens from Yukon and Northwest Territories), we created a class for “north of sixty” (degrees of latitude) territories, TR.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 21%">
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 23%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td><strong>Province/Territory</strong></td>
<td></td>
<td><strong>Live now (n)</strong></td>
<td></td>
<td><strong>Formative region (n)</strong></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>BC</td>
<td></td>
<td>628</td>
<td></td>
<td>444</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>AB</td>
<td></td>
<td>663</td>
<td></td>
<td>506</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>SK</td>
<td></td>
<td>277</td>
<td></td>
<td>278</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>MB</td>
<td></td>
<td>327</td>
<td></td>
<td>295</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>ON</td>
<td></td>
<td>450</td>
<td></td>
<td>520</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>QC</td>
<td></td>
<td>123</td>
<td></td>
<td>105</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>NB</td>
<td></td>
<td>47</td>
<td></td>
<td>36</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>NS</td>
<td></td>
<td>46</td>
<td></td>
<td>45</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>PE</td>
<td></td>
<td>62</td>
<td></td>
<td>45</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>NL</td>
<td></td>
<td>42</td>
<td></td>
<td>42</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>TR</td>
<td></td>
<td>35</td>
<td></td>
<td>10</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td><strong>Canada total</strong></td>
<td></td>
<td><strong>2700</strong></td>
<td></td>
<td><strong>2326</strong></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>US</td>
<td></td>
<td>93</td>
<td></td>
<td>127</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>UK</td>
<td></td>
<td>0</td>
<td></td>
<td>32</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>others</td>
<td></td>
<td>208</td>
<td></td>
<td>482</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td><strong>TOTAL</strong></td>
<td></td>
<td><strong>3001</strong></td>
<td></td>
<td><strong>2967</strong></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Table 1: Absolute frequencies: locations</p>
<p>Response numbers by age and gender are depicted in Figure 1. As can be seen, the cohort 20-24 is best represented, with females typically outnumbering males. Non-binary respondents are best represented in the cohorts from 20-49.</p>
</section>
<section id="results-discussion" class="level1">
<h1>4 Results &amp; Discussion</h1>
<p>In the first section we aim to connect public discourse and use of language reference tools with language attitudinal data. We will use several single variables and some indices that will, overall, allow us to interpret the strength of the notion of “Canadian English” as a standard variety in the minds of its speakers and with it the role of the pluricentricity of English in North America.</p>
<p><strong>Attitudinal autonomy in CanE</strong></p>
<p>Figure 2 offers an overview of six key questions which were asked of Canadian residents (this includes transient residents, e.g.&nbsp;foreign students). Combining the answers of “Definitely yes” and “Probably yes”, the notion of an autonomously “Canadian way of speaking” is confirmed by 70.1%, with 9% undecided. Compared with 81.1% from 2009 from a six-point scale, the present five-point scale probably more closely reflects the actual state of attitudes. Similar percentages, 68% see CanE as a “distinct kind of English”, like American or British English. On the question of spelling, the sample is more divided, with more undecided ones (26.4%) than definite yeses (24.8%). This is somewhat add odds with almost 39% “definitely” confirming that Canadian universities should encourage Canadian spelling and a clear 78% wish to have a Canadian spelling option in software applications, with 12% undecided. Lastly, in terms of a free digital dictionary of CanE, nearly 71% claim they would use it.</p>
<p>Figure 1: Absolute frequencies: age and gender for formative years in Canada</p>
<p>With such answers the linguistic autonomy of Standard Canadian English seems well enshrined at this point, confirming the 2009 data overall and showing considerable differentiation from the early 1980s, when “Americanization” was the most virulently discussed attribute of Canadian English. This change in outlook is remarkable and warrants a closer look at the social distribution of those who recognize Canadian English – most commonly through its standard that had been documented and fully codified as a distinct variety of English by 1967 (Gregg 1993, Dollinger 2019: 131-32).</p>
<p><strong>Familiarity with “Standard Canadian English”</strong></p>
<p>While “Canadian English”, as a slur, dates to 1857 (DCHP-3, s.v.&nbsp;“Canadian English”), “Standard Canadian English” (StCanE) is a concept that has been discussed in linguistic circles only since the 1970s. It is in pluricentric theory the key concept whose understanding is a <em>sine-qua-non</em> for an appreciation of the linguistic autonomy of a variety, i.e.&nbsp;Canadian English. In the public and in schooling, however, uptake of StCanE as a term and autonomous concepts has been slower. While the public perception of a “Canadian English” has been strong, related discourse is subject to considerable fluctuation.&nbsp; Figure 3 (left) shows data to that effect, which compares the use of Canadian dictionary titles in domestic media since the 1970s with the frequencies of the term “Canadian English” (“Canadian Newsstream” database) from 1980 to the end of 2024, shown in Figure 3 (right).</p>
<p>In general, the 1980s and 1990s were a period of increasing language awareness in Canada, with the uptake of Canadian dictionary titles lagging behind an increase or decrease of the phrase “Canadian English” in the media by a period of five years. The more the concept is discussed, the more Canadian dictionary titles are used as reference sources in the media. The years 1996-1998 have been the most productive years in Canadian English dictionary publishing so far, with four full-size titles appearing. The sole winner, the <em>Canadian Oxford Dictionary</em> of this Canadian dictionary war, however, was shut down in 2008, which led to US titles being the most prevalent ones, as Figure 3 (left) shows. Today, the <em>Canadian English Dictionary</em> is scheduled to take over that function when finished (Chew 2025).</p>
<p>That is as much detail as can be extracted from corpus searches. We aim use the current study to fill in some gaps in interpretation. Figure 4 summarizes the respondent’s general familiarity with the term “Standard Canadian English” or “Canadian Standard English” by region, that is by their formative years (“have you heard the term…”). &nbsp;We assigned a province/territory or country to those who spent at least nine years in their ages 0-18 in one location and show the Canadian as well as the US and UK responses for comparison.</p>
<p>Figure 4 depicts the 10 Canadian provinces (BC to NL) and one plot for the three Canadian Territories (TR), completed by the UK and US respondents. Most often respondents reported having heard the term “Standard Canadian English” in New Brunswick (NB), followed by Ontario (ON), British Columbia (BC), Alberta (AB), Quebec (QC), Manitoba, Sasktachewan. These seven provinces show significant differences between yes and no. The Maritime provinces, Nova Scotia (NS) do not reach significance, though more have heard the term, while in Prince Edward Island (PEI) those who haven’t heard are in the majority, there’s a tie in the Territories (TR). The UK respondents are more exposed to the term than people raised in Manitoba (MB), Newfoundland and Labrador (NL) and <u>Saskatchewan (SK)</u>.</p>
<p>The Americans (US) in our sample, all of whom likely with some ties to Canada as an artefact of our data collection method (snowball method), are more familiar with the term than Nova Scotians (NS) and Prince Edward Islanders (PE). The assumption is that if speakers are familiar with Standard Canadian English they are more likely to comprehend the social relevance of the variety as a marker of identity. Such awareness would therefore be strongest in New Brunswick (which sets it apart from the other Atlantic Provinces NS, PE and NL), followed by Ontario, then BC and Alberta.</p>
<p>Figure 5 shows exposure to “Standard Canadian English” with respondents’ status of multilingualism. Monolingual speakers, socialized in Canada, are significantly less likely to “have heard” of “Standard Canadian English” or “Canadian Standard English”. Monolinguals are more likely to have a “default” of “English unspecified” as a variety and need to learn to appreciate the special characteristics of Standard Canadian English.</p>
<p>Figure 5 shows that Multilinguals who &nbsp;were raised in Canada are significantly more likely than Monolinguals to have heard about Standard CanE. What, however, do they understand by the term, which is used in specialist circles, but very little in public discourse today (Figure 3 right, 2020-24 period)?</p>
<p>An open answer field solicited definitions of Standard Canadian English, with the options to decline (“don’t know what it is”, “do know it but cannot describe it well”), was designed to yield only the answers of the confident respondents in that aspect, some of which are reproduced in Table 2 below:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 1%">
<col style="width: 54%">
<col style="width: 1%">
<col style="width: 38%">
<col style="width: 1%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Responses to “Do you know what “Standard Canadian English?”</td>
<td></td>
<td>Social characteristics</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>1.&nbsp;&nbsp;&nbsp;&nbsp; “English used <strong>across the country</strong>”</td>
<td></td>
<td>15-19, US-raised, female now in Montreal for UG), fluent English &amp; Spanish, French advanced; Ashkenazi</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>2.&nbsp;&nbsp;&nbsp;&nbsp; “It’s a <strong>normalised pronunciation</strong> of English that one would hear in somewhat formal broadcasts from the <strong>CBC</strong>”</td>
<td></td>
<td>early 60s, male, but L2 multilingual, English &amp; French fluent, Italian intermediate, Spanish &amp; Chinese beginner</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>3.&nbsp;&nbsp;&nbsp;&nbsp; <strong>Useless spelling</strong> when the <strong>USA</strong> is right next door and is most of our media</td>
<td></td>
<td>Bilingual Quebecker, lived in QC, BC and in the USA during formative years, 30-34, male.</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>4.&nbsp;&nbsp;&nbsp;&nbsp; “I assume it is the Canadian English <strong>of the dominant group (socially, in number)</strong> and that corresponds to what one would hear in <strong>mainstream media</strong>.”</td>
<td></td>
<td>Montrealer, 50s, female, Francophone + Anglophone (Bilingual in the official sense), intermed. Italian</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>5.&nbsp;&nbsp;&nbsp;&nbsp; English but with <strong>Canadian (more British)</strong> spellings and vocab, maybe pronunciation.</td>
<td></td>
<td>University student in 2<sup>nd</sup> year, 15-19, male, from Edmonton, AB, monolingual</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>6.&nbsp;&nbsp;&nbsp;&nbsp; It is the English that includes words used in a <strong>Canadian context</strong>, or spelled in the way Canadians are accustomed to spelling them.</td>
<td></td>
<td>Nanaimo, female BC resident, 40-44, grew up in Ontario, Anglophone with intermediate French</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>7.&nbsp;&nbsp;&nbsp;&nbsp; Canadian English per the <strong>Canadian Oxford dictionary</strong>. Or <strong>“CBC English”</strong></td>
<td></td>
<td>BC resident, female, 30-34, grew up in Calgary, AB, multilingual</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>8.&nbsp;&nbsp;&nbsp;&nbsp; The English dialect largely spoken in <strong>Ontario and western Canada</strong></td>
<td></td>
<td>Saskatchewanian, male, 30-34, multilingual&nbsp; (fluent in English, French); Spanish, Japanese, Mandarin (intermediate)</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>9.&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;It is the standard dialect used in Canadian classrooms, by <strong>Canadian media</strong>, by <strong>Canadian government</strong>, etc.</td>
<td></td>
<td>Montrealer, Italian-Canadian, 20-24, multilingual</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>10.&nbsp;&nbsp; English spoken by people who primarily <strong>grew up</strong> or acquired their English <strong>in Canada</strong></td>
<td></td>
<td>Chinese-Canadian Montrealer, fluent in Mandarin and English, intermed. French, 20-24</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Table 2: Select responses to the question “Do you know what “Standard Canadian English” is?</p>
<p>Of the ten descriptions of Standard Canadian English, notions of widespread use (1, 4, 6), media (2, 4, 7, 9), more British influence (5), a regional dimension (8) and socialization in Canada (10) are recurring themes, with occasional sceptics (3). What is striking is that the attribute of “educated”, normally a mainstay in standard variety definitions, is absent. Trudgill &amp; Hannah (2017: 6) speak of a “North American English (NAmEng), meaning English as written and spoken by educated speakers in the United States of America and Canada”, though a definition rooted in educated speech does not feature prominently in the responses, with only three in the entire sample mentioning “educated” speakers.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The next question asked, “Do you know what ‘Standard Canadian English’ (or ‘Canadian Standard English’) is?”. Figure 6 only shows the ones that were able to answer “Yes” to that question. There were two Yes-categories: “Yes, but I can’t describe it well” and those that did offer a description (n for both Yes-categories was 1513 or 48.2%). While the data in Figure 6 is significant for age, visual inspection shows that starting at 25-29 virtually no change is visible in the two lines. This means that the youngest age cohorts 14 and under, 15-19 and 20-24 are the ones that produce significance for age. In other words: once the university years are over and basic education is completed, there is no change in knowledge about the standard: only some 25% of those how know what Standard Canadian English is are able to describe it in some form.</p>
<p>One additional issue is that the older teenagers are the age cohort that is the least likely to know what StCanE is. Only 10 of the 116 youngsters aged 15-19-years and socialized in Canada (162 overall, including newcomers) know what “Standard Canadian English” is, which raises the question how English is taught at Canadian schools, without using this key concept in pluricentric theory. Failure to teach the concept of linguistic pluricentricity in school may offer an explanation why the monolingual speakers (Figure 5) are less likely to have heard about StCanE than multilinguals, which leaves the monolinguals potential for linguistic identity formation untapped.</p>
<p><strong>“Canadian way” of speaking</strong></p>
<p>Another way of gauging the awareness of StCanE is to ask about a “Canadian way” of speaking, (Dollinger 2020: 63, Table 4.5). Without using linguistic terminology of standard varieties, the respondents answer with a personal assessment or impression. Figure 7 shows the results for Canadian residents and those who spent their formative years in Canada (left). Those growing up in Canada see consistently more a “Canadian way of speaking”. Figure 7 (right) divides the “formative years” on the left by gender, suggesting that females overall play a more important role than males in that process, with non-binaries numerally too weak to make a difference.</p>
<p>The recognition of this expression of linguistic autonomy seems to be&nbsp; predominantly female-led. In terms of age, we see a slight decrease among the younger cohorts, which to a degree will correlate with education: as we will see below, the more educated a respondent is, the more likely they are to recognize Standard Canadian English.</p>
<p><strong>Standard Language Attitude Index (SLAI)</strong></p>
<p>A further attempt to gauge awareness of standard varieties is via a composite Index SLAI. The original concept of combining five factors was reduced to four due to low internal consistency with the last factor (Have you heard the term “Standard Canadian English”), which was treated separately above. SLAI averages the following four variables at the level of the individual respondent.<a href="#_ftn1">[1]</a></p>
<ul>
<li><p><strong>Spell_uni</strong>: Do you think Canadian university departments should encourage Canadian English spelling in academic work?</p></li>
<li><p><strong>spell</strong>: Do you think that Canadian spelling is important (e.g.&nbsp;“colour” instead of “color”, “familiarize” not “familiarise”)?</p></li>
<li><p><strong>distinct</strong>: In your opinion, is Canadian English a distinct kind of English (e.g.&nbsp;similar to American English being distinct from British English)?</p></li>
<li><p><strong>cdn_way</strong>: In your opinion, is there a Canadian way of speaking English?</p></li>
</ul>
<p>An internal consistency test of the SLAI revealed an overall Cronbach 𝛼 of 0.7 suggesting that the index meets the consistency threshold for research work proposed by Nunnally &amp; Bernstein (1994).</p>
<p>Figure 8 shows the distribution of SLAI with Education as explanatory variable, a significant effect (p&lt;0.05 for all education levels). Figure 8 shows that recognition of StCanE increases regularly with highest level of education completed.</p>
<p>When we introduce Gender into the mix, which tested as significant, a more nuanced picture emerges that allows us to distinguish between English monolingual speakers and multilingual speakers on another level. Among the monolinguals, shown in Figure 9 on the left, gender is more important as a predictor than among the multilinguals (shown on the right). Specifically, monolingual (young) females with only an elementary school education are considerably more positive towards Standard Canadian English, expressed via a higher SLAI, than their male counterparts. A gap that is second widest among those with a graduate education. In the undergraduate segment, non-binary students are more sceptical than both males and females.</p>
<p>For the multilinguals (right), males and females align much more closely with one another, with the notable exception of those who only completed elementary school, where males are again more sceptical. Note that non-binaries are, from high-school on, more sceptical, except those with a postgraduate degree, which have a slightly higher SLAI than both females and males in their cohort.&nbsp;</p>
<p>While the difference between male and female participants is clearest among respondents with <em>either</em> elementary education&nbsp;<em>or</em>&nbsp;those with a graduate degree, the countertrends for males on the one hand and females on the other can be shown in Figure 10:</p>
<p>In monolinguals females have a higher SLAI than their multilingual peers. The same holds for non-binary speakers. For men, however, the trend is reverse, as multilingual speakers have a higher SLAI than monolingual speakers, which leads to a split between males and females as a significant variable overall.</p>
<p>The effects explored here were entered into a linear regression model predicting respondent’s aggregate values for SLAI. Region, gender and education were found to make highly significant predictions, as shown in Table 3 below.</p>
<p><strong>“Ethnic Orientation Index” and “English Use Index”</strong></p>
<p>Given that speakers’ status as multilingual speakers has effects on the recognition of StCanE, the effect of a speaker’s ethnic group and one’s orientation towards that group – or lack thereof – seemed like a reasonable choice for further exploration. Ethnic heritage group membership has been a recent focus in work on CanE (e.g.&nbsp;Nagy 2024, Nagy, Hoffman &amp; Walker 2020), going back to at least Hoffman &amp; Walker (2010), whose concept of an EOI – Ethnic Orientation Index – was adapted for written questionnaire surveys such as ours and scaled down from 32 to just five questions:</p>
<p>Yielding scores from 0 (not at all, not applicable) to 3 (very much) for each attribute, the scores range from 0 to 15. In the data set, 896 respondents reported an EOI (of the 2326 who spent their formative years in Canada, see Table 1). Of these 896 emic self-declarations, we accepted an etic EOI for 820. The remaining 76 self-reported distinct cultural group memberships of “White Canadian Settler”, or “English/ Scottish Canadian”, which we excluded.&nbsp;</p>
<p>Ethnic Orientation has no correlation with SLAI or with the key question of a “Canadian way of speaking”. As shown in Figure 4, Education does a good job in tuning speakers, regardless of their ethnic backgrounds, onto a positive wavelength for Canadian English; it does, however, do a much less impressive job teaching the necessary concepts for a full appreciation of pluricentric Englishes, as just a little over half of the population have ever heard of StCanE (Figure 4).</p>
<p>Another measure is the “English Use Index” (EUI), inspired by Chambers &amp; Heisler’s (1999) “Language Use Index”. The EUI gauges how frequently English is used based on six contexts:</p>
<p>Average EUI is significantly different between the monolinguals and self-reported bi- and multilinguals. The low EUI (some non-English use) speakers are less convinced and high EUI speakers (considerable non-English use) even more so. The EUI suggests that monolinguals (EUI = 0) are driving the identification with Canadian English.&nbsp; This is striking, as they are also the ones who are less likely to have heard of StCanE (Figure 5). The higher the EUI, the less likely one is to conceptualize Canadian English as an autonomous variety, though one is more likely to have heard about StCanE. The finding is consistent with multilingual children and their parents in a study in BC and Alberta (Dollinger et al.&nbsp;2024). It may seem counter-intuitive that those who speak more than one language regularly would be less open towards the autonomy of Standard Canadian English but in the lived experiences – one may have learned American English in the Philippines before coming to Canada or UK English in Hong Kong – the Canadian dimension in English seems to be less important for the multilinguals who use their languages in one of the contexts.</p>
<p>While we know from previous work that local terms “do not register with the bi- and multilinguals to the same degree” as in the long-term resident population (Dollinger 2012: 529), this explanation does not apply to the results shown here to the same degree as all spent at least 9 years from ages 0-18 in Canada. While among multilingual newcomers the adoption of Canadian items is an exception (only 1 in 5 local forms was used, in that study the term <em>homo milk</em> ‘whole milk’) (ibid: 529-30), some of this group’s often predominant UK forms reinforce Canadian English features that seem to “preserve some of the Canadian markers that local speakers seem to be losing” (ibid: 530).</p>
</section>
<section id="conclusion" class="level1">
<h1>5 Conclusion</h1>
<p>The results show that roughly one in two respondents knows what StCanE is, while just 13% of respondents were able to offer a definition. As Figure 6 has shown, knowledge about the standard is low before age 25-29, it appears that the conceptual work relating to Canadian English is not carried out sufficiently in high school and elementary school but only at the post-secondary level. This is a remarkable feature of Canadian English, with Canadian schools displaying a kind of laissez-faire attitude regarding the linguistic standard (e.g.&nbsp;spell one way, but consistently).</p>
<p>Students in elementary and secondary students are linguistically socialized in an unspecified construct of “standard English”, schematized in Figure 15 on the left. The pluricentric notion, shown in the right panel, with separate reference points for each national standard, appears late in the respondents’ learning biographies, after high school, and then captures only a fraction of the domestic population. Ethnicity does not affect preferences for a pluricentric view, but, as Figure 13 suggests, the frequency of English use does: the less often one uses English, the less likely one is to construct Canadian English as one of the “peaks” of English in Figure 15. The Canadian (functional) monolinguals are less likely to have heard of the domestic standard.</p>
<p>The previous literature attests to an increase in linguistic awareness between the late 1970s and the early 2000s. In the 1977 UVic study a question about the CBC as the bearer of the Canadian standard was asked, and questions about subjective feelings when Canadians are mistaken for an American or British speaker, as well as whether a separate entity of Canadian English existed. These were reported in a composite index, however. An only mildly positive outlook in this category of “linguistic national identity” (+0.193 on a scale from -1 to +1) led to the conclusion that the group did “not feel very strongly about speaking a distinctive variety” (Gulden 1979: 58). In the early 2000s, 81% reported that, by and large, they believed in a “Canadian way of speaking English”.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In the present study, among those having grown up in Canada, a very similar share of 81.4% recognize a Canadian way of speaking in 2023. Women appear to be leading that change and maintenance of language awareness of Canadian English (Figure 7). The cognitive identification with Canada has important linguistic and perceptual repercussions. Swan and Babel (2018: 155), for instance, suggest that language ideologies and attitudes play a role in discriminating Canadians from Americans in perception studies, for which their data shows that “Seattle and Vancouver listeners are generally not able to differentiate a talker as being from Seattle or Vancouver” (p.&nbsp;153), with the caveat that Seattleites are mildly sensitive to Canadian production stereotypes, which renders Seattleites more accurate in detecting Vancouverites than vice versa. Yet, 73% claimed in 2009 to be able to tell Americans from Canadians.</p>
<p>Language attitudes are an important factor in “language making” (Krämer et al.&nbsp;2022) and variety making, especially so for non-dominant varieties (Dollinger 2025b). Rather than declaring socially meaningful discrimination as not existent based on a lack of categoricity in production, as has been done in the Austrian context (e.g.&nbsp;Elspaß &amp; Niehaus 2014: 50), the process of enregisterment and cognitive constructions by the speakers, including nationality, are actuated.</p>
<p>Education is a key factor in that process of conceptually constructing a national standard variety. While the teaching of a “banal nationalism” (Billig 1995) in Canada – the bias that comes with teaching from a certain geographical and sociopolitical point of view – may be considered as somewhat more muted than in other places, certainly in the United States, it is nonetheless present. This can be witnessed in both the reported findings that direct questions on national identity produce more positive results than indirect ones (as Warkentyne 1983 already reported) and, more recently, the reinvigorated Canadian patriotism following the Trump tariffs and annexation threats in 2025.</p>
<p>In the linguistic context, Oakes states that linguistic pluricentricity “cannot rely solely on linguistic data, but must also take into account the role of representations and attitudes” (Oakes 2021: 55). One could dismiss the Canadian case, or that of any other non-dominant variety, as a case of language ideology, which is usually frowned upon. However, “while language ideologies [mediating between social structure and linguistic practice] certainly help to shape language representations and attitudes, the latter should nonetheless be considered distinct” (ibid: 56-57). The language attitudes surveyed and reported here are subjective norms that may overlap with socially constructed ideology of “Canadian-ness” but are not identical with the latter. Subjective claims of linguistic identity involving the Canadian angle may easily be confused with nationalistic thinking, though that would deprive the speakers of non-dominant varieties, for whom their identity aspects as members of smaller nations are generally important, of their linguistic autonomy and recognition.</p>
<p>Linguistic insecurity, as one aspect of language attitudes, is an indicator for the varying social prestige of varieties but not a good indicator of their relevance. Non-dominant variety speakers (e.g.&nbsp;Canadian English, Austrian German, Belgian Dutch, Quebec French, Catalan, Finnish Swedish) are confronted with linguistic insecurity in many of their encounters, which raises, to the degree that “linguistic insecurity reflects a perceived threat to individuals’ sense of linguistic dignity or self-esteem”, the issue to “recognize that there is also an ethical dimension to the question of linguistic pluricentricity”, which Oakes terms “linguistic pluricentric justice” (p.&nbsp;58). Clearly, sociolinguistic practice ought to consider the emic angle as equally important, if not more so, than etic statements that will inevitably exert some hegemonic force (see Dollinger 2025b for a drastic example of field-internal presuppositions).</p>
<p>We have seen in Figure 2 that only 22.2% answered “Definitely yes” to the question whether CanE was a distinct kind of English, like BrE and AmE, while 45.8 chose “Probably yes”. The lower degree of certainty in these answers suggests that a degree of linguistic insecurity is present. Although 78% would want to see a “Canadian English option” in software, the relatively low exposure rates to Standard Canadian English as a term (just around 50% anywhere but in New Brunswick and Ontario, where it is higher, Figure 4) result in a somewhat diffuse picture at present regarding the strength of linguistic autonomy of CanE. While linguistic autonomy is detectable in these data points, it is expressed more cautionarily.</p>
<p>Similar results, from Austrian German, are interpreted not as a logical consequence of dominant and non-dominant standards and their intersections, but as two “norms of orality” of one standard, as, it is claimed, “a single … conceptualization of ‘standard’ does not meet the complex linguistic situation” in Austria (Koppensteiner &amp; Lenz 2020: 59-60). However, a “transnational unmarked” variety is taken for granted and not questioned (ibid). Such interpretation is consistent with a suggested, but controversially discussed, One Standard German Axiom (OSGA) (in German: Axiom des Einheitsdeutschen, Dollinger 2019b: 14, 2025b).</p>
<p>Pluricentric interpretations are occasionally critiqued as “lend[ing] themselves to nationalistic views and interpretations and exploitations precisely because they are interested predominantly in linguistic perception rather than production” (e.g.&nbsp;Schneider 2022: 470-71). Such critique confirms philological and linguistic disciplinary narratives that have become enshrined and that generally foreground particular perspectives of more established, more hegemonic interpretations of “language making” or “variety making”. In more extreme cases, pluricentric interpretations of non-dominant varieties – such as Canadian English, Austrian German or Brazilian Portuguese – are presented as “restrict[ing] the usage areas of standard varieties to national boundaries” based on “purely political criteria” (Elspaß 2025: 24), which undercuts non-dominant linguistic identity constructions and the principle of pluricentric linguistic justice (Oakes 2021) in lieu of something else (e.g.&nbsp;Herrgen’s 2015 ‘denationalization’ claim of German, critiqued in Dollinger 2019a: 79-84).</p>
<p>Linguistic data are dynamic and greatly influenced by speakers attitudes, as we have aimed to show for Canadian English. The etic angle – linguistic production – makes little social sense without the emic – linguistic attitudes and perceptions (e.g.&nbsp;Scherr &amp; Ziegler’s 2023 etic deconstruction of pluricentric German). When, for instance, large majorities of speakers perceive their younger standard variety as real (e.g.&nbsp;c.&nbsp;85% in Austria, 78% in CanE from Figure 2), we ought to question the role of a sociolinguistics that seems to deny the relevance of such statements.</p>
<p>In the Canadian context, the connection between linguistic identity and linguistic varieties is more widely accepted, and thus the relevance of attitudinal factors (e.g.&nbsp;Preston 2013) in linguistic claims of Canadianness. The idea of a One Standard English Axiom (OSGA) seems absurd, especially in the light of World Englishes. It is these attitudinal factors in the context of “pluricentric linguistic justice” that are to be considered, which is rather different from assumed “defenses of the concept of pluricentricity” (Schneider 2022: 470). It is not ideology that is the key point of pluricentric theory, but a consideration of the language attitudes of non-dominant speakers and a concession that standard varieties are dynamically shaped. In the Austrian case, it seems as if a similar expression of Austrian identities via an Austrian standard – which de facto happens routinely (de Cillia &amp; Ransmayr 2019: Abb. 36) – is theoretically preempted via OSGA (see Dollinger 2019b) or allowed. In the present Canadian case, however, such notions of a single standard are of no social relevance and the study of the domestic Canadian standard can proceed without linguistic opposition.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The importance of education was highlighted by significant correlations in Figures 8 and 9 via a composite index (SLAI – Standard Language Attitude Index, referring to Standard Canadian English). SLAI confirms that for those growing up in Canada, no correlations with ethnic orientations can be discerned (Figure 12). Those who are themselves multilingual tend to orient themselves more towards StCanE if they are female or non-binary, while male multilinguals are more sceptical (Figure 10). Male scepticism towards the non-dominant StCanE is consistent, for instance in Figure 7 (right panel).</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The frequency of English use (EUI) is, like multilingualism, a more important factor for the Canadian standard. Those who use English the least (Figure 13) also consider CanE its own distinct variety the least, while, conversely, monolingual speakers do so the most. These two groups show a significant difference (with more frequent English users in Canada in between, but not significant).</p>
<p>As outlined in the beginning, language representations and attitudes are fuelled by wider social contexts. While Canadian national identity was on the rise in the 1970s, linguistic identity was not. This has shifted in the early 2000s and is still ongoing. However, today there is, in comparison to the early 2000s, little to no public discourse about the linguistic identity of Anglophone Canadians, as shown in Figure 1. It will remain to be see if and to what degree linguistic work on the unique angle of Canadian English (<a href="http://www.canadianenglishdictionary.ca">www.canadianenglishdictionary.ca</a>) may enrich Canadian public discourse.&nbsp;</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Billig, Michael. 1995. <em>Banal Nationalism</em>. London: Sage.</p>
<p>Boberg, Charles. 2000. Geolinguistic diffusion and the U.S.-Canada border. <em>Language Variation and Change</em> 12: 1-24.</p>
<p>Boberg, Charles. 2005. The North American Regional Vocabulary Survey: new variables and methods in the study of North American English. <em>American Speech</em> 80: 22-60.</p>
<p>Boberg, Charles. 2008. Regional phonetic differentiation in Standard Canadian English. <em>Journal of English Linguistics</em> 36(2): 129-154.</p>
<p>Chambers, J. K. (1980) Linguistic variation and Chomsky’s “homogeneous speech community”. In Murray Kinloch and A. B. House (eds), <em>Papers from the Fourth Annual Meeting of the Atlantic Provinces Linguistic Association</em> (pp.&nbsp;1–31). Fredericton: University of New Brunswick.</p>
<p>Chambers, J. K. 1994. An introduction to dialect topography. <em>English World-Wide</em> 15: 35-53.</p>
<p>Chambers, J. K. 2000. Region and language variation. <em>English World-Wide</em> 21(2): 169-199.</p>
<p>Chambers, J. K. and Troy Heisler. 1999. Dialect Topography of Québec City English. <em>Canadian Journal of Linguistics</em> 44(1): 23-48.</p>
<p>Clarke, Sandra (ed.). 1993. <em>Focus on Canada</em>. Amsterdam: Benjamins.</p>
<p>Clyne, Michael G. 1984. <em>Language and Society in the German-speaking Countries</em>. New York : Cambridge University Press.</p>
<p>Clyne, Michael G. 1995. <em>The German Language in a Changing Europe</em>. New York: Cambridge University Press.</p>
<p>DCHP-3 = Dollinger, Stefan and Margery Fee (eds). 2025.&nbsp;<em>DCHP-3: The Dictionary of Canadianisms on Historical Principles, Third Edition.</em>&nbsp;Vancouver, BC: University of British Columbia,&nbsp;<a href="https://www.dchp.ca/dchp3">www.dchp.ca/dchp3</a>. DOI:&nbsp;<a href="https://doi.org/10.17613/hr345-77f43" class="uri">https://doi.org/10.17613/hr345-77f43</a>&nbsp;(Published 15 May 2025).</p>
<p>De Cillia, Rudolf and Jutta Ransmayr. 2019. <em>Österreichisches Deutsch macht Schule? Bildung und&nbsp; Deutschunterrricht im Spannungsfeld von sprachlicher Variation und Norm.</em> Vienna: Böhlau. <a href="https://austria-forum.org/web-books/en/osterreichdeutsch00de2019isds" class="uri">https://austria-forum.org/web-books/en/osterreichdeutsch00de2019isds</a></p>
<p>Dollinger, Stefan. 2012. The western Canada-US border as a linguistic boundary: The roles of L1 and L2 speakers. <em>World Englishes</em> 31(4): 519–533.</p>
<p>Dollinger, Stefan. 2019a. <em>Creating Canadian English: the Professor, the Mountaineer, and a National Variety of English.</em> Cambridge: Cambridge University Press.</p>
<p>Dollinger, Stefan. 2019b. <em>The Pluricentricity Debate: On Austrian German and Other Germanic Standard Varieties.</em> London: Routledge.</p>
<p>Dollinger, Stefan. 2020. English in Canada. In: <em>Handbook of World Englishes, Second edition</em>, ed.&nbsp;by Cecil Nelson, Zoya Proshina &amp; Daniel Davis, 52-69. Malden, MA: Blackwell-Wiley.</p>
<p>Dollinger, Stefan. 2025a. Eberhard Kranzmayer’s dovetailing with Nazism: His fascist years and the ‘One Standard German Axiom (OSGA)’.&nbsp;<em>Discourse &amp; Society</em>&nbsp;<em>36</em>(2): 147-179.</p>
<p>Dollinger, Stefan. 2025b. Dialectology as “language making”: hegemonic disciplinary discourse and the One Standard German Axiom (OSGA). In <em>(Dia)lects in the 21st Century: Selected Papers from</em> Methods in Dialectology XVII (Mainz, 2022), ed.&nbsp;by Susanne Wagner &amp; Ulrike Stange-Hundsdörfer, 287-318. Berlin: LangSci Press.</p>
<p>Elspass, Stephan. 2025. Pluriareal languages and the case of German. In Meer &amp; Durgasingh (eds.), 15-44.</p>
<p>Freake, Yvette. 2023. So you think you speak Canadian English: a study of language regard and lexical variation of English-speaking Canadians. Ph.D.&nbsp;thesis, York University, Toronto. Program in Linguistics.</p>
<p>Gregg, Robert J. 1993. Canadian English lexicography. In Clarke (ed.), 27-44.</p>
<p>Gulden, Brigitte K. [now Halford, Brigitte K.] 1979. Attitudinal factors in Canadian English usage. Victoria: University of Victoria, Department of Linguistics, MA thesis.</p>
<p>Herrgen, Joachim. 2015. Entnationalisierung des Standards. Eine perzeptionslinguistische Untersuchung zur deutschen Standardsprache in Deutschland, Österreich und der Schweiz. In: Lenz &amp; Glauninger (Eds.), pp.&nbsp;139–164.</p>
<p>Hoffman, Michol F. and James A. Walker. 2010. Ethnolects and the city: Ethnic orientation and linguistic variation in Toronto English. <em>Language Variation and Change</em> 22: 37-67.</p>
<p>Krämer, Philipp, Leena Kolehmainen &amp; Ulrike Vogl. 2022. What is “language making”? <em>International Journal for the Sociology of Language</em> 274: 1–27.</p>
<p>Koppensteiner, Wolfgang &amp; Alexandra Lenz. 2020. Tracing a standard language in Austria using methodological microvariations of verbal and matched guise technique. <em>Linguistik Online</em> 102 2/20: 47-82.</p>
<p>Leitner, Gerhard. 1992. English as a pluricentric language. In <em>Pluricentric languages. Differing norms in different nations,</em> Michael Clyne (ed.), 179-237. Berlin: Mouton de Gruyter.</p>
<p>McKinnie, Meghan &amp; Jennifer Dailey-O’Cain. 2002. A perceptual dialectology of Anglophone Canada from the perspective of young Albertans and Ontarians. In: Preston &amp; Long (eds), Vol. 2: 277-94.</p>
<p>Meer, Philipp &amp; Ryan Durgasingh (eds.) 2025.&nbsp;<em>Pluricentricity and Pluriareality:&nbsp;Dialect,&nbsp;Variation, and&nbsp;Standards.</em> Amsterdam: Benjamins.&nbsp;</p>
<p>Muhr, Rudolf. 2012. Linguistic dominance and non-dominance in pluricentric languages: A typology. In R. Muhr (Ed.), <em>Non-dominant varieties of pluricentric languages: Getting the picture</em> (pp.&nbsp;23-48). Berne: Lang.</p>
<p>Muhr, Rudolf. 2025. <em>Fundamentals of a General Theory of Pluricentric Languages</em>. Graz: PCL-Press, <a href="https://pcl-press.org/publications/fundamentals-of-a-general-theory-of-pluricentric-languages/" class="uri">https://pcl-press.org/publications/fundamentals-of-a-general-theory-of-pluricentric-languages/</a></p>
<p>Nagy, Naomi. 2024. <em>Heritage Languages</em>. Cambridge: Cambridge University Press.</p>
<p>Nagy, Naomi, Michol F. Hoffman, James A. Walker. 2020. How do Torontonians hear ethnic identity? <em>TWPL</em> 42: 1-18.</p>
<p>Nunnally, J.C. and Bernstein, I.H. 1994. The assessment of reliability. <em>Psychometric Theory</em> 3: 248-292.</p>
<p>Oakes, Leigh. 2021. Pluricentric linguistic justice: a new ethics-based approach to pluricentricity in French and other languages. <em>Sociolinguistica</em> 35(1): 49-71.</p>
<p>Owens, Thompson W. and Paul M. Baker. 1984. Linguistic insecurity in Winnipeg: validation of a Canadian index of linguistic insecurity. <em>Language in Society</em> 13: 337-350.</p>
<p>Pratt, Terrence K. 1993. The hobglobin of Canadian English spelling. In S. Clarke (ed.), 45-64.</p>
<p>Preston, Dennis R. &amp; Daniel Long (eds.) 1999-2002. <em>Handbook of Perceptual Dialectology. Vol. 1, Vol. 2.</em> Amsterdam: Benjamins.</p>
<p>Preston, Dennis. 2013. Linguistic insecurity forty years later. <em>Journal of English Linguistics</em> 41(4), 304–331.</p>
<p>Sadlier-Brown, Emily. 2012. Across the country, across the border: homogeneity and autonomy of Canadian Raising. <em>World Englishes</em> 31(4): 534-548.</p>
<p>Scherr, E &amp; Ziegler A. (2023). A question of dominance: statistically approaching grammatical variation in German standard language across borders. <em>Journal of Linguistic Geography</em> 11, 91–103.</p>
<p>Schneider, Edgar W. 2022. Parameters of epicentral status. <em>World Englishes</em> 41: 462–474.</p>
<p>Swan, Julia T. and Molly Babel. 2018. Dialect Identification Across a Nation-State Border: Perception of Dialectal Variants in Seattle, WA and Vancouver, BC. <em>University of Pennsylvania Working Papers in Linguistics</em> 24(2): 147-56.</p>
<p>Trudgill, Peter &amp; Jean Hannah. 2017. <em>International English. A Guide to Varieties of English Around the World</em>. 6<sup>th</sup> ed.&nbsp;Abingdon: Taylor and Francis.</p>
<p>Warkentyne, Henry J. 1983. Attitudes and language behavior. <em>Canadian Journal of Linguistics</em> 28: 71-76.</p>
<p>Warkentyne, Henry J. and A. C. Brett. 1981. British and American influences on Canadian English. <em>Working Papers of the Linguistic Cirlce of the University of Victoria</em> 1(2): 294-310.</p>
<p><a href="#_ftnref1">[1]</a> Questions with answer choices on a four-point Likert scale were rescaled to match the spread of a five-point scale to enable us to meaningfully average the four responses.</p>
<p><a href="#_ftnref1">[1]</a> Canada-US Trade Agreement in 1988, NAFTA in 1994, the European Union 1993 and the founding of the World Trade Organization in 1995</p>
<p><a href="#_ftnref2">[2]</a> <a href="https://www.academia.edu/129153656/" class="uri">https://www.academia.edu/129153656/</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>